version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sqli_demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demopass
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro

  web:
    image: php:8.1-apache
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
