repos:
  - repo: https://github.com/koalaman/shellcheck
    rev: v0.9.0
    hooks:
      - id: shellcheck
        stages: [commit]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.6.0
    hooks:
      - id: detect-secrets
        stages: [commit]
