FROM php:8.1-apache

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      default-libmysqlclient-dev \
      default-mysql-client \
      libzip-dev zip unzip git ca-certificates && \
    docker-php-ext-install mysqli pdo_mysql && \
    apt-get purge -y --auto-remove default-libmysqlclient-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html
EXPOSE 80
